<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>214e80a5-8ed5-4222-9761-e09eb7ff1bdf</testSuiteGuid>
   <testCaseLink>
      <guid>161d826e-3050-48f0-ab13-f7724b857207</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>e553268a-4832-4845-864c-2ce0dd2cdaf5</id>
         <masked>false</masked>
         <name>password</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Demo/DataDrivenTestingDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d88acbb7-df63-42b2-a5aa-37032a13606c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d88acbb7-df63-42b2-a5aa-37032a13606c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>ac17b869-ffd8-4abb-a1e5-63c6579daebb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d88acbb7-df63-42b2-a5aa-37032a13606c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>e553268a-4832-4845-864c-2ce0dd2cdaf5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
