<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TestingAbdul</name>
   <tag></tag>
   <elementGuidId>781ca020-e554-40f0-9742-c0fd72006447</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#my-profile-header > div.css-lipffl > div.css-67arje</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='my-profile-header']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>66fdeb87-431d-4fa2-b5db-23e3027a1e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-67arje</value>
      <webElementGuid>d915c176-166b-49ef-921f-4fb6bcc7bfe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TestingAbdul</value>
      <webElementGuid>c19c4995-8f8e-499d-ac4f-ed8a0ae5b86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-profile-header&quot;)/div[@class=&quot;css-lipffl&quot;]/div[@class=&quot;css-67arje&quot;]</value>
      <webElementGuid>ff7d529f-3be6-4bc2-9e6d-db601ff14d23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='my-profile-header']/div/div</value>
      <webElementGuid>9475b1d2-3e1c-4179-99aa-9208f74d76c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toko'])[1]/following::div[3]</value>
      <webElementGuid>6f393c0c-2079-4284-834c-271ae717d525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::div[19]</value>
      <webElementGuid>3eca4b6b-30eb-4aca-9aaa-89afccbfbe18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestingAbdul'])[2]/preceding::div[2]</value>
      <webElementGuid>bb1f4cfa-aa9d-4372-ad83-f9200f351018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member Silver 2'])[1]/preceding::div[3]</value>
      <webElementGuid>93128d6f-c46c-4445-9c38-2b6b773ebe74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TestingAbdul']/parent::*</value>
      <webElementGuid>27a861e8-9e74-4367-8ea9-def0c6be4c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div</value>
      <webElementGuid>b31f4d49-2836-4464-afc4-3551b08f57ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'TestingAbdul' or . = 'TestingAbdul')]</value>
      <webElementGuid>cc6f572f-d9bf-4eb6-a5e4-af5b8d6582d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
