<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor HP atau Email_email-phone</name>
   <tag></tag>
   <elementGuidId>a0df1797-614a-487b-9c62-2751fd8e909a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email-phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email-phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56904d7b-31d0-4afc-a215-90d48b139026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>c7fe3f9a-52b5-46ae-894e-de369931dc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>53f8b9ea-4914-4abb-a77d-c81ab3dc4dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email-phone</value>
      <webElementGuid>080c401f-5ca7-465b-b022-7dd9df7b1076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>a48dddd4-ebe8-4f81-9440-60792d24058b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>email-phone-input</value>
      <webElementGuid>bf04943a-ea38-4d58-aed9-84d0e7600c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-3017qm exxxdg63</value>
      <webElementGuid>36ef789c-d151-420f-a473-8c059b0deff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TestingAbdul</value>
      <webElementGuid>89789a88-331f-4bd6-b23f-7685ba6a68b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-phone&quot;)</value>
      <webElementGuid>8ab95cc2-830a-42c9-b641-0a117fc3a3ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email-phone']</value>
      <webElementGuid>40c2dbfc-d9a2-47e3-a9b6-718d918c19a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>1d5b8780-b2ee-425a-88ce-7c294cba176d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'email-phone' and @type = 'email']</value>
      <webElementGuid>e5a9555e-c346-4cbe-a6a8-da7a0f84b20d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
