<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AcceptedW3CCapabilityKeys</name>
   <tag></tag>
   <elementGuidId>91b7b52a-a203-48cc-8357-b504fc81cd85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'AcceptedW3CCapabilityKeys')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.colFirst > a[title=&quot;class in org.openqa.selenium&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2c72f275-f991-4bdb-92d3-98a4e5f58f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>AcceptedW3CCapabilityKeys.html</value>
      <webElementGuid>71aeed39-4ac9-4403-8ccd-a069e3a9c452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium</value>
      <webElementGuid>5ee600ab-55f6-43a3-aa67-997d8a29b846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AcceptedW3CCapabilityKeys</value>
      <webElementGuid>cbd95f49-b962-4841-8664-afcf0b1306aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;contentContainer&quot;]/ul[@class=&quot;blockList&quot;]/li[@class=&quot;blockList&quot;]/table[@class=&quot;typeSummary&quot;]/tbody[2]/tr[@class=&quot;altColor&quot;]/th[@class=&quot;colFirst&quot;]/a[1]</value>
      <webElementGuid>7a7809e9-0cba-44db-b837-b02ee6440c5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AcceptedW3CCapabilityKeys')]</value>
      <webElementGuid>a495f73c-4ad8-4f84-b2a5-2155b0cb7636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[2]/following::a[1]</value>
      <webElementGuid>33392f4e-c5dd-4b1b-aa2f-b02badde7353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class'])[2]/following::a[1]</value>
      <webElementGuid>c6124fb3-9746-47e2-a92d-74005110e95d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BuildInfo'])[1]/preceding::a[1]</value>
      <webElementGuid>242e5adb-a288-4372-8417-d10974c0f9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reads information about how the current application was built.'])[1]/preceding::a[2]</value>
      <webElementGuid>3531e224-665c-4ce1-b491-1fff14201b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AcceptedW3CCapabilityKeys']/parent::*</value>
      <webElementGuid>668c1af5-069c-405d-ae9f-7f42b4c8ecff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'AcceptedW3CCapabilityKeys.html')]</value>
      <webElementGuid>87b38c71-d9a1-493a-8456-c78d81e3330d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/table/tbody[2]/tr/th/a</value>
      <webElementGuid>6090f387-ba03-4ccb-8c4c-063c134b8fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'AcceptedW3CCapabilityKeys.html' and @title = 'class in org.openqa.selenium' and (text() = 'AcceptedW3CCapabilityKeys' or . = 'AcceptedW3CCapabilityKeys')]</value>
      <webElementGuid>c4d0f26b-d055-4c84-af47-9121b4a7f94f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
