<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Keluar</name>
   <tag></tag>
   <elementGuidId>c28499a9-3fb2-4dd9-8a04-010f4e1abb09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1juts7j</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='my-profile-overlay']/div/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c2a6f8bc-c4d1-477a-87f2-1cd1d8785957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1juts7j</value>
      <webElementGuid>757922d7-2a69-450e-acce-f319eadf7005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keluar</value>
      <webElementGuid>7511639f-d40a-46ec-ad71-8f539a9242b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-profile-overlay&quot;)/div[@class=&quot;css-gochc6&quot;]/div[@class=&quot;css-1pxyyq2&quot;]/div[@class=&quot;css-1kux3a9&quot;]/div[@class=&quot;css-1juts7j&quot;]</value>
      <webElementGuid>f8ecccdb-a0d3-4b9a-893a-577f92232baf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='my-profile-overlay']/div/div[2]/div[2]/div</value>
      <webElementGuid>6e176778-ccfd-4811-ba9b-532c2348b6f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengaturan'])[1]/following::div[1]</value>
      <webElementGuid>cdee1b17-e88c-43fc-8ded-818007636410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toko Favorit'])[1]/following::div[1]</value>
      <webElementGuid>995cfef1-5910-4265-a758-1e018fdda3d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='apple pencil'])[1]/preceding::div[2]</value>
      <webElementGuid>774b0d6d-5004-43fa-b008-5d7613a3da89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='oppo a54'])[1]/preceding::div[2]</value>
      <webElementGuid>e8c4cfb5-d1c7-4b2b-98ba-1fad10bf549c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keluar']/parent::*</value>
      <webElementGuid>fe570a94-ac99-4e8a-aebd-ba1325c92992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div[2]/div[2]/div</value>
      <webElementGuid>cedd4d82-c542-4487-8ddf-c3b1601ac601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Keluar' or . = 'Keluar')]</value>
      <webElementGuid>8550eb99-feb7-4d8c-8e7e-a0ad37e85b1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
